#cloud-config

package_update: true
package_upgrade: true

apt:
  preserve_sources_list: false
  add_apt_repo_match: ^[\w-]+:\w
  sources:
    kubernetes.list:
      source: "deb  http://apt.kubernetes.io/  kubernetes-xenial  main"
      keyserver: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
      keyserver: https://download.docker.com/linux/ubuntu/gpg

packages:
  - curl
  - apt-transport-https
  - vim
  - git
  - gnupg2
  - software-properties-common
  - ca-certificates
  - uidmap
  - jq

runcmd:
  - echo $HOME >> /home/ubuntu/test.txt
  - whoami >> /home/ubuntu/test.txt
